### ISSUE TITLE
Update country info?

### ISSUE THREAD

**Issue by KyleAMathews** [richorama/country-code-lookup#1]
Hey, super happy I came across this today. Exactly what I need for a project (being able to lookup region/continents by country code). Curious where the data in the csv comes from? Probably could use updated after 2 years and I'd be happy to do it.

**Comment by richorama** [comment]
Good question! I can't remember where I got the information from now :¬(

I'll have a look around and see if I can remind myself. I'll add references to the sources when I find them...
