### ISSUE TITLE
Country details using country currency code.

### ISSUE THREAD

**Issue by kayoderock** [richorama/country-code-lookup#18]
I want to be able to get country details, using the country's currency ISO code as the key. 

Or better still I should be able to get any country's details by specifying the key I wanna search with.

Example .Find({key: "currency", value: "USD"})

**Comment by richorama** [comment]
Hi @kayoderock,

You can indeed use the ISO code as the key:

```
const lookup = require('country-code-lookup')
lookup.byIso('GB')
lookup.byIso('GBR')
``` 

If you want to search by any key, you could write a function like this:

```
function searchBy(key, value) {
  lookup.countries.find(x => x[key] === value);
}
```

I hope that helps?

**Comment by kayoderock** [comment]
Definitely, thank you.

**Comment by kayoderock** [comment]
@richorama the countries object returned does not have the currency in it.

`continent: "Africa"
region: "Western Africa"
country: "The Gambia"
capital: "Banjul"
fips: "GA"
iso2: "GM"
iso3: "GMB"
isoNo: "270"
internet: "GM"`

This is all been returned.

**Comment by richorama** [comment]
correct, I'm afraid that this library does not include currency information. I wouldn't be opposed to adding it in if you know of a reliable data source.

**Comment by kayoderock** [comment]
@richorama sure, I would check it out. I would not mind contributing that to it.

**Comment by richorama** [comment]
👍

**Comment by kayoderock** [comment]
@richorama what do you think of this [country currencies](https://www.wikiwand.com/en/List_of_circulating_currencies).

I was hoping to add the currencies up, but some countries got more than one currency, how do you think its best to add the country with more than one currency.
