### ISSUE TITLE
can't lookup ByCountry for 

### ISSUE THREAD

**Issue by dixitk13** [richorama/country-code-lookup#20]
I was just trying to use the library, looks like the following countries aren't returning for `byCountry` method: 

```
[
  "UK",
  "S. Korea",
  "Czechia",
  "UAE",
  "Hong Kong",
  "Channel Islands",
  "Palestine",
  "DRC",
  "Faeroe Islands",
  "Brunei ",
  "Congo",
  "Bahamas",
  "Macao",
<--didn't read after this -->
  "Myanmar",
  "St. Vincent Grenadines",
  "MS Zaandam",
  "Gambia",
  "Turks and Caicos",
  "Cabo Verde",
  "CAR",
  "Vatican City",
  "St. Barth",
  "Falkland Islands",
  "Caribbean Netherlands",
  "Saint Pierre Miquelon"
]
```
M not sure, if all of these are valid countries. Feel free to close iff not.

**Comment by richorama** [comment]
I think your country names don’t quite line up. It’s ‘United Kingdom’ for example.

**Comment by TriBuiQuang** [comment]
Dear mr. Richorama,
i can't look up country "Hong Kong" , it's return null when i search it , 
but in https://www.iban.com/country-codes , they had , can you fix it ?

**Comment by richorama** [comment]
It was in as `Hong Kong (China)` - I have fixed this and republished. Thanks for letting me know!
