### ISSUE TITLE
Search by "United States of America" fails

### ISSUE THREAD

**Issue by JCaye** [richorama/country-code-lookup#21]
byCountry('United States') works. However, while the official name listed here: https://www.iban.com/country-codes is "United States of America", byCountry('United States of America') returns null. Is it possible to add support for multiple names?

**Comment by richorama** [comment]
Hi @JCaye, I'm not opposed to having a list of aliases against each country name, allowing a search by multiple possible names, I wonder where we could get a list of these names from. I also think that the countries should display their IBAN names. I'll have a think about what to do.

**Comment by lukakralj** [comment]
Hi @richorama, a list of alternative country names on [Wikipedia](https://en.wikipedia.org/wiki/List_of_alternative_country_names) could be a good start.

**Comment by itaisatati** [comment]
Hi, is this suggestion still relevant?
I'd happily add the the IBAN names to the country-objects.
