### ISSUE TITLE
Should lower or upper case

### ISSUE THREAD

**Issue by ObadaMoustafa** [richorama/country-code-lookup#30]
Hello When I search by country using lower case it returns `null` .. you should lower or upper case the value to be as same as your data to give the right answer in all cases.

**Comment by richorama** [comment]
This library is really intended for converting between ISO and FIPS codes for countries. Given that country names can often be quite long and can take several forms (`United States of America`, `USA`, `America`, `US`) I don't think it's a very useful search index.

It is possible to retrieve the country list from the library and do your own fuzzy matching.
