### ISSUE TITLE
How can I query for England, Wales, Scotland, & Northern Ireland country iso codes?

### ISSUE THREAD

**Issue by jtara1** [richorama/country-code-lookup#32]
England, Wales, & Scotland are countries (in GB)
Northern Ireland is a province (in UK)

```
const CountryCodeLookup = require('country-code-lookup');

let countryName = 'England';
const result = CountryCodeLookup.byCountry(countryName); // yields no results
const { iso2, iso3 } = result ?? {};

console.log(iso2, iso3, countryName);
```

I'd expect iso2 to be `'GB'` for the 4 countries.

Also, bc all data is unpacked into the default export of this lib, we don't get autocomplete in node.js repl.

**Comment by richorama** [comment]
Yes, I live in England, it's a confusing place.

England, Wales, Scotland and Northern Ireland all fall under the same ISO code (alpha 2, alpha 3 and numeric):
https://www.iso.org/obp/ui/#iso:code:3166:GB 

There is also only one FIPS code (UK).

So whilst you could have 4 records that all have the same code, but with different country names, it would make the library more confusing to work with. Perhaps a compromise here would be to have an array of country names for each record. It's been previously suggested that alternative country names could be useful as well (USA / United States of America) but I'm not aware of a good data source for this.

This library does not attempt to model geopolitical entities. It is designed purely as a mechanism to convert between these 4 codes.

The entities do have separate ISO 3166-2 codes, but this library does not include that code.

I am interested in your point around the autocomplete not working. Could you elaborate on that? Or feel free to submit a PR for it.

**Comment by jtara1** [comment]
>Also, bc all data is unpacked into the default export of this lib, we don't get autocomplete in node.js repl.

nevermind, this hasn't been a problem checking again

**Comment by jtara1** [comment]
libpostal address_parser will parse these 4 places as "state"

England, Wales, Scotland, and Northern Ireland
