### ISSUE TITLE
Handle country codes with "-"

### ISSUE THREAD

**Issue by karthik2265** [richorama/country-code-lookup#37]
`
lookup.byIso('BQ-BA') // BQ-BA represents bonaire but this throws an error
`

[wikipedia link](https://en.wikipedia.org/wiki/ISO_3166-2:BQ#:~:text=Currently%20for%20Bonaire%2C%20Sint%20Eustatius%20and%20Saba%2C%20special,alpha-2%20code%20of%20Bonaire%2C%20Sint%20Eustatius%20and%20Saba.)

could you please update the package to handle this.

**Comment by richorama** [comment]
Hi, thanks for raising this issue. This library does not support ISO 3166-2, and doesn't go to territory level. You can pass in 'BQ' though, and get back 'Bonaire'.
